version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15

    working_directory: /go/src/github.com/daisy1754/errmsg
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go build -v ./...
      - run: go test -v ./...
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
