version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15

    working_directory: /go/src/github.com/daisy1754/errmsg
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go build -v ./...
      - run: go test -coverpkg=github.com/daisy1754/errmsg,github.com/daisy1754/errmsg/errors -coverprofile=coverage.profile -v ./...
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - codecov/upload:
          file: coverage.profile
